preload = /home/slumpy_666/.config/hypr/walls/copland.png

# Replace the comma with 'DP-2' (the name found in your logs)
wallpaper = DP-2,/home/slumpy_666/.config/hypr/walls/copland.png

# Optional: Disable splash text to keep it clean
splash = false
